name: myqlmdask
channels:
  - myqlm
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.12
  - anytree=2.12.1
  - astroid=3.3.5
  - asttokens=2.4.1
  - attrs=24.2.0
  - aws-c-auth=0.7.31
  - aws-c-cal=0.7.4
  - aws-c-common=0.9.28
  - aws-c-compression=0.2.19
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.10
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.7
  - aws-c-s3=0.6.6
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.20
  - aws-crt-cpp=0.28.3
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.9.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - bitarray=2.9.2
  - bitstring=4.2.3
  - bokeh=3.5.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.1
  - ca-certificates=2024.8.30
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - clarabel=0.7.1
  - click=8.1.7
  - cloudpickle=3.0.0
  - cmake=3.30.5
  - colorama=0.4.6
  - contourpy=1.3.0
  - cvxpy=1.5.3
  - cvxpy-base=1.5.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - cytoolz=1.0.0
  - dask=2024.9.1
  - dask-core=2024.9.1
  - dask-expr=1.1.15
  - dbus=1.13.6
  - decorator=5.1.1
  - dill=0.3.9
  - distributed=2024.9.1
  - double-conversion=3.3.0
  - ecos=2.0.14
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - flake8=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - freetype=2.12.1
  - fsspec=2024.9.0
  - gflags=2.2.2
  - glog=0.7.1
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - iniconfig=2.0.0
  - ipython=8.28.0
  - isort=5.13.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.1
  - libclang13=19.1.1
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.10.1
  - libdeflate=1.22
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgl=1.7.0
  - libglib=2.82.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.1.0
  - libgoogle-cloud=2.29.0
  - libgoogle-cloud-storage=2.29.0
  - libgrpc=1.65.5
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.1
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libntlm=1.4
  - libopenblas=0.3.27
  - libopengl=1.7.0
  - libosqp=0.6.3
  - libparquet=17.0.0
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=17.0
  - libprotobuf=5.27.5
  - libqdldl=0.1.5
  - libre2-11=2023.11.01
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.49.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=3.0.1
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - msgpack-python=1.1.0
  - munkres=1.1.4
  - myqlm=1.10.4
  - myqlm-clinalg=0.2.2
  - myqlm-contrib=1.9.5
  - myqlm-fermion=1.1.4
  - myqlm-simulators=1.9.5
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - networkx=3.4
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openldap=2.6.8
  - openssl=3.3.2
  - orc=2.0.2
  - osqp=0.6.7.post0
  - pandas=2.2.3
  - parso=0.8.4
  - partd=1.4.2
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - ply=3.11
  - prettytable=3.11.0
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyarrow-hotfix=0.6
  - pycodestyle=2.12.1
  - pycparser=2.22
  - pydoe=0.3.8
  - pyflakes=3.2.0
  - pygments=2.18.0
  - pylint=3.3.1
  - pyparsing=3.1.4
  - pyside6=6.7.3
  - pysocks=1.7.1
  - pytest=8.3.3
  - python=3.12.7
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.12
  - pyyaml=6.0.2
  - qat-anapli=0.0.1
  - qat-comm=1.6.0
  - qat-core=1.10.0
  - qat-devices=0.3.0
  - qat-fusion=0.1.0
  - qat-hardware=1.4.0
  - qat-lang=3.1.0
  - qat-quops=1.3.4
  - qat-variational=1.5.0
  - qdldl-python=0.1.5.post2
  - qhull=2020.2
  - qlmaas=1.10.2
  - qt6-main=6.7.3
  - qutip=5.0.4
  - re2=2023.11.01
  - readline=8.2
  - referencing=0.35.1
  - rhash=1.4.4
  - rpds-py=0.20.0
  - s2n=1.5.5
  - scipy=1.14.1
  - scs=3.2.7
  - setuptools=75.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - stack_data=0.6.2
  - svgwrite=1.4.3
  - tblib=3.0.0
  - tk=8.6.13
  - tomli=2.0.2
  - tomlkit=0.13.2
  - toolz=1.0.0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.2.3
  - wayland=1.23.1
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.2
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.5
  - xorg-xorgproto=2024.1
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zict=3.0.0
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.6.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cachetools==5.5.0
      - charset-normalizer==3.4.0
      - cirq==1.4.1
      - cirq-aqt==1.4.1
      - cirq-core==1.4.1
      - cirq-google==1.4.1
      - cirq-ionq==1.4.1
      - cirq-pasqal==1.4.1
      - cirq-rigetti==1.4.1
      - cirq-web==1.4.1
      - comm==0.2.2
      - cryptography==43.0.1
      - debugpy==1.8.7
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - duet==0.2.9
      - fastjsonschema==2.20.0
      - fqdn==1.5.1
      - funcsigs==1.0.2
      - google-api-core==2.21.0
      - google-auth==2.35.0
      - googleapis-common-protos==1.65.0
      - grpc-interceptor==0.15.4
      - grpcio==1.66.2
      - grpcio-status==1.62.3
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - ibm-cloud-sdk-core==3.21.0
      - ibm-platform-services==0.57.1
      - idna==3.10
      - ipykernel==6.29.5
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jax==0.4.34
      - jaxlib==0.4.34
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - mistune==3.0.2
      - ml-dtypes==0.5.0
      - mock==5.1.0
      - mpmath==1.3.0
      - myqlm-interop==1.9.6
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - packaging==23.2
      - pandocfilters==1.5.1
      - pbr==6.1.0
      - projectq==0.8.0
      - prometheus-client==0.21.0
      - proto-plus==1.24.0
      - protobuf==4.25.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyjwt==2.9.0
      - pyopenssl==24.2.1
      - pyquil==4.14.3
      - pyspnego==0.11.1
      - python-json-logger==2.0.7
      - python-rapidjson==1.20
      - pytz==2024.2
      - pyzmq==26.2.0
      - qcs-api-client-common==0.10.0
      - qcs-sdk-python==0.20.1
      - qiskit==1.2.4
      - qiskit-ibm-runtime==0.30.0
      - qiskit-ignis==0.7.1
      - qiskit-terra==0.46.3
      - quantum-grove==1.7.0
      - quil==0.13.1
      - requests==2.32.3
      - requests-ntlm==1.3.0
      - retworkx==0.15.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpcq==3.11.0
      - rsa==4.9
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - rustworkx==0.15.1
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - stevedore==5.3.0
      - symengine==0.13.0
      - sympy==1.13.3
      - terminado==0.18.1
      - thrift==0.20.0
      - tinycss2==1.3.0
      - types-deprecated==1.2.9.20240311
      - types-python-dateutil==2.9.0.20241003
      - uri-template==1.3.0
      - wand==0.6.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
