channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.11
  - anyio=4.3.0
  - anytree=2.8.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - attr=2.5.1
  - attrs=23.2.0
  - beautifulsoup4=4.12.3
  - bitarray=2.9.2
  - bitstring=4.2.2
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - clarabel=0.7.1
  - comm=0.2.2
  - contourpy=1.2.1
  - cvxpy=1.5.1
  - cvxpy-base=1.5.1
  - cycler=0.12.1
  - dbus=1.13.6
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.5.1
  - ecos=2.0.13
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.80.2
  - glib-tools=2.80.2
  - graphite2=1.3.13
  - gst-plugins-base=1.24.3
  - gstreamer=1.24.3
  - harfbuzz=8.5.0
  - icu=73.2
  - idna=3.7
  - importlib_resources=6.4.0
  - ipykernel=6.29.3
  - ipython=8.24.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.2
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jsonpointer=2.4
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_widgets=3.0.10
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang13=18.1.5
  - libcups=2.3.3
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgomp=13.2.0
  - libgpg-error=1.49
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libllvm18=18.1.5
  - libnsl=2.0.1
  - libogg=1.3.4
  - libopenblas=0.3.27
  - libopus=1.3.1
  - libosqp=0.6.3
  - libpng=1.6.43
  - libpq=16.3
  - libqdldl=0.1.7
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libstdcxx-ng=13.2.0
  - libsystemd0=255
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mpg123=1.32.6
  - munkres=1.1.4
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nb_conda=2.2.1
  - nb_conda_kernels=2.5.1
  - nbclassic=1.0.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.100
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.0
  - osqp=0.6.3
  - overrides=7.7.0
  - packaging=24.0
  - pandas=2.2.2
  - pandoc=3.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - ply=3.11
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pydoe=0.3.8
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qdldl-python=0.1.7.post2
  - qt-main=5.15.8
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - qutip=5.0.1
  - readline=8.2
  - referencing=0.35.1
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.1
  - scipy=1.13.0
  - scs=3.2.4.post1
  - send2trash=1.8.3
  - setuptools=69.5.1
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.2
  - svgwrite=1.4.3
  - terminado=0.18.1
  - tinycss2=1.3.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.41
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - install==1.3.5
      - myqlm==1.9.5
      - myqlm-clinalg==0.1.3
      - myqlm-contrib==1.9.2
      - myqlm-fermion==1.1.1
      - myqlm-simulators==1.9.3
      - qat-core==1.8.3
