# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    paths-ignore: 
      - 'doc/**'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      #- uses: actions/checkout@v4
    - name: create environment with mamba
    - uses: conda-incubator/setup-miniconda@v3
      with:
        mamba-version: "*"
        miniconda-version: "latest"
        use-only-tar-bz2: true
        environment-file: environment.yml
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: anaconda-client-env
      #- name: Set up Python 3.12
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: 3.12
    - run: |
        conda info
        conda list

    - name: Install with flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
